; DEBUG < INFO < WARNING < Exception < Error < Critical

[loggers]
keys=consoleLogger,fileLogger,comboLogger

[loggers_consoleLogger]
level=DEBUG
handlers=consoleHandler

[loggers_fileLogger]
level=DEBUG
handlers=fileHandler

[loggers_comboLogger]
level=DEBUG
handlers=consoleHandler,fileHandler

[handler_consoleHandler]
class=StreamHandler
formatter=detailedFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=TimedRotatingFileHandler
formatter=detailedFormatter
args=('./logs/logfile.log', 'midnight', 1, 30)

[formatter_simpleFormatter]
format=[%(asctime)s] %(message)s

[formatter_detailedFormatter]
format=[%(asctime)s] [%(levelname)s] %(message)s
