from python_library.define.enum import IENUM

class E_SENSOR_TYPE(IENUM):
    ALL = "ALL"
    GNSS = "GNSS"
    LIDAR = "LIDAR"
    CAMERA = "CAMERA"
    IMU = "IMU"
    TIMER = "TIMER"

class E_TIMER(IENUM):
    TIMER = "TIMER"

class E_GNSS(IENUM):
    GNSS = "GNSS"

class E_IMU(IENUM):
    IMU = "IMU"

class E_LIDAR(IENUM):
    AT128_ROOF_FRONT = "AT128_ROOF_FRONT"
    AT128_ROOF_RIGHT = "AT128_ROOF_RIGHT"
    AT128_ROOF_REAR = "AT128_ROOF_REAR"
    AT128_ROOF_LEFT = "AT128_ROOF_LEFT"
    RSBP_BUMP_FRONT = "RSBP_BUMP_FRONT"
    RSBP_BUMP_RIGHT = "RSBP_BUMP_RIGHT"
    RSBP_BUMP_REAR = "RSBP_BUMP_REAR"
    RSBP_BUMP_LEFT = "RSBP_BUMP_LEFT"

class E_CAMERA(IENUM):
    AM20_FRONT_CENTER_RIGHT_DOWN = "AM20_FRONT_CENTER_RIGHT_DOWN"
    AM20_FRONT_RIGHT_REAR = "AM20_FRONT_RIGHT_REAR"
    AM20_REAR_CENTER_RIGHT = "AM20_REAR_CENTER_RIGHT"
    AM20_FRONT_LEFT_REAR = "AM20_FRONT_LEFT_REAR"
    AM20_REAR_RIGHT_EDGE = "AM20_REAR_RIGHT_EDGE"
    AM20_LEFT_REAR_EDGE = "AM20_LEFT_REAR_EDGE"
    AM20_FRONT_CENTER_LEFT_UP = "AM20_FRONT_CENTER_LEFT_UP"
    AM20_FRONT_CENTER_RIGHT_UP = "AM20_FRONT_CENTER_RIGHT_UP"
    AM20_FRONT_RIGHT_FRONT = "AM20_FRONT_RIGHT_FRONT"
    AM20_FRONT_LEFT_FRONT = "AM20_FRONT_LEFT_FRONT"
